build:  
   image: node:latest 
   stage: build   
   script:    
      # Install vuecli    
      #- npm install -g @vue/cli@latest    
      # Install dependencies    
      - npm install -g npm@latest
      - echo "Install all dependecies -- npm install -- .............................."
      - npm install      
      - echo "Build the project -- npm run build -- .............................."
      # Build App    
      - npm run build  
   artifacts:
      paths:
          # Build folder
         - dist/
      expire_in: 1 hour

   cache:
      paths:
         - node_modules/ 
variables:
  AWS_ACCESS_KEY_ID: "***"
  AWS_SECRET_ACCESS_KEY: "***"

deploy: 
   image: python:latest 
   stage: deploy 
   script: 
      - echo "Deploying to aws"
      - pip install awscli 
      - aws s3 sync dist/ s3://example.com --include "*" 
